version: '3.0'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: test-1:1:1
      KAFKA_TOPIC_METADATA_REFRESH_INTERVAL_MS: "60000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # canal:
  #   image: canal/canal-server:v1.1.4

