version: '3.0'
services:
  zookeeper:
    image: zookeeper:3.4.14
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.132.129
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_CREATE_TOPICS: test-1:1:1
      KAFKA_TOPIC_METADATA_REFRESH_INTERVAL_MS: "60000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  canal:
    image: canal/canal-server:v1.1.4
    environment:
      - canal.instance.mysql.slaveId=54321
      - canal.instance.master.address=mysql:3306
      - canal.instance.dbUsername=wordpress
      - canal.instance.dbPassword=wordpress
      - canal.instance.parser.parallel=false
      - canal.instance.filter.regex=wordpress\.wp_users
      - canal.mq.dynamicTopic=.*\..*
      - canal.zkServers=zookeeper:2181
      #canal.properties 配置
      - canal.serverMode=kafka
      - canal.mq.servers=kafka:9092
    depends_on:
      - zookeeper
      - kafka

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      # - ./data/mysql:/var/lib/mysql
      - ./data/conf.d:/etc/mysql/conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_can_you
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306

  wordpress:
    depends_on:
        - mysql
    image: wordpress
    restart: always
    ports:
      - 8180:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    # volumes:
    #   - ./data/html:/var/www/html
